name: jogo_cultura_paraense
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.29.3
  shared_preferences: ^0.5.1+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  share: '>=0.6.5+4 <2.0.0'
  flutter_bloc: ^6.1.1
  graphql: ^3.1.0
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/images/LoadingBackground.png
    - lib/images/mesoregioes.png
    - lib/images/sudoesteparaense.png
    - lib/images/baixoamazonas.png
    - lib/images/sudesteparaense.png
    - lib/images/nordesteparaense.png
    - lib/images/marajo.png
    - lib/images/metropolitana.png
    - assets/images/findGame/bosqueRA.jpg
    - assets/images/findGame/mangalG.jpeg
    - assets/images/findGame/00.png
    - assets/images/findGame/01.png
    - assets/images/findGame/02.png
    - assets/images/findGame/03.png
    - assets/images/findGame/04.png
    - assets/images/findGame/05.png
    - assets/images/findGame/06.png
    - assets/images/findGame/07.png
    - assets/images/findGame/08.png
    - assets/images/findGame/09.png
    - assets/images/findGame/010.png
    - assets/images/findGame/011.png
    - assets/images/findGame/012.png
    - assets/images/findGame/013.png
    - assets/images/findGame/014.png
    - assets/images/findGame/015.png
    - assets/images/findGame/016.png
    - assets/images/findGame/017.png
    - assets/images/findGame/018.png
    - assets/images/findGame/019.png
    - assets/images/findGame/020.png
    - assets/images/findGame/021.png
    - assets/images/findGame/022.png
    - assets/images/findGame/023.png
    - assets/images/findGame/024.png
    - assets/images/findGame/start_button.png
    - assets/images/findGame/no_button.png
    - assets/images/findGame/hint_button.png
    - assets/images/findGame/how_to.png
    - assets/audio/completetask_0.mp3
    - assets/audio/explosion.wav
    - assets/audio/win_sound.wav
    - assets/audio/hint.wav
    - assets/audio/wrong.wav
    - assets/images/cooking_game/acai.png
    - assets/images/cooking_game/acucar.png
    - assets/images/cooking_game/arroz.png
    - assets/images/cooking_game/boi.png
    - assets/images/cooking_game/camarao.png
    - assets/images/cooking_game/carangueijo.png
    - assets/images/cooking_game/coco.png
    - assets/images/cooking_game/creme_leite.png
    - assets/images/cooking_game/cupuacu.png
    - assets/images/cooking_game/farinha_tapioca.png
    - assets/images/cooking_game/farofa.png
    - assets/images/cooking_game/filhote.png
    - assets/images/cooking_game/goma_tapioca.png
    - assets/images/cooking_game/jambu.png
    - assets/images/cooking_game/leite_coco.png
    - assets/images/cooking_game/leite_condensado.png
    - assets/images/cooking_game/macaxeira.png
    - assets/images/cooking_game/maniva.png
    - assets/images/cooking_game/ovos.png
    - assets/images/cooking_game/pato.png
    - assets/images/cooking_game/porco.png
    - assets/images/cooking_game/tucupi.png
    - assets/images/cooking_game/panela.png
    - assets/images/cooking_game/dica.png
    - assets/images/cooking_game/bg.jpeg
    - assets/images/cooking_game/tutorial0.jpg
    - assets/images/cooking_game/tutorial1.jpg
    - assets/images/cooking_game/tutorial2.jpg
    - assets/images/running_game/arvore.png
    - assets/images/running_game/boto.png
    - assets/images/running_game/cobra_grande.png
    - assets/images/running_game/curupira.png
    - assets/images/running_game/iara.png
    - assets/images/running_game/mapinguari.png
    - assets/images/running_game/matinta.png
    - assets/images/running_game/muiraquita.png
    - assets/images/running_game/vitoria_regia.png
    - assets/images/running_game/jogador.png
    - assets/images/running_game/aranha.png
    - assets/images/running_game/onca.png
    - assets/images/running_game/pedra.png
    - assets/images/running_game/poca.png
    - assets/images/running_game/sapo.png
    - assets/images/running_game/tronco.png
    - assets/images/running_game/bg.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
